// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChannelEntry struct {
	Name      string   `json:"name"`
	Replaces  *string  `json:"replaces"`
	Skips     []string `json:"skips"`
	SkipRange *string  `json:"skipRange"`
}

type Icon struct {
	Base64data string `json:"base64data"`
	Mediatype  string `json:"mediatype"`
}

type OlmBundle struct {
	Schema        string          `json:"schema"`
	Package       string          `json:"package"`
	Name          string          `json:"name"`
	Image         string          `json:"image"`
	Properties    []*Property     `json:"properties"`
	RelatedImages []*RelatedImage `json:"relatedImages"`
}

type OlmChannel struct {
	Schema  string          `json:"schema"`
	Package string          `json:"package"`
	Name    string          `json:"name"`
	Entries []*ChannelEntry `json:"entries"`
}

type OlmMeta struct {
	Schema  string      `json:"schema"`
	Package string      `json:"package"`
	Blob    interface{} `json:"blob"`
}

type OlmPackage struct {
	Schema         string  `json:"schema"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	DefaultChannel string  `json:"defaultChannel"`
	Icon           *Icon   `json:"icon"`
}

type Property struct {
	Type  string      `json:"type"`
	Value interface{} `json:"value"`
}

type RelatedImage struct {
	Image string  `json:"image"`
	Name  *string `json:"name"`
}
